const contractDetails = [
  {
    contract_decimals: 0,
    contract_name: '#LetsWalk',
    contract_ticker_symbol: '#LetsWalk',
    contract_address: '0x0825f050e9b021a0e9de8cb1fb10b6c9f41e834c',
    supports_erc: ['erc20', 'erc1155'],
    logo_url: 'https://logos.covalenthq.com/tokens/1/0x0825f050e9b021a0e9de8cb1fb10b6c9f41e834c.png',
    last_transferred_at: '2021-09-27T16:52:30Z',
    native_token: false,
    type: 'nft',
    balance: null,
    balance_24h: null,
    quote_rate: 0.0,
    quote_rate_24h: null,
    quote: 0.0,
    quote_24h: null,
    nft_data: [
      {
        token_id: '10032',
        token_balance: null,
        token_url: null,
        supports_erc: null,
        token_price_wei: null,
        token_quote_rate_eth: null,
        original_owner: null,
        external_data: null,
        owner: null,
        owner_address: null,
        burned: null,
      }
    ],
  },
  {
    contract_decimals: 0,
    contract_name: 'Top Cat Club',
    contract_ticker_symbol: 'Top Cat Club',
    contract_address: '0x0a437c82af985c0a49700d0b2e678bcae7b58574',
    supports_erc: ['erc20', 'erc1155'],
    logo_url: 'https://logos.covalenthq.com/tokens/1/0x0a437c82af985c0a49700d0b2e678bcae7b58574.png',
    last_transferred_at: '2022-05-07T03:27:20Z',
    native_token: false,
    type: 'nft',
    balance: null,
    balance_24h: null,
    quote_rate: 0.0,
    quote_rate_24h: null,
    quote: 0.0,
    quote_24h: null,
    nft_data: [
      {
        token_id: '50',
        token_balance: null,
        token_url: null,
        supports_erc: null,
        token_price_wei: null,
        token_quote_rate_eth: null,
        original_owner: null,
        external_data: null,
        owner: null,
        owner_address: null,
        burned: null,
      }
    ],
  },
  {
    contract_decimals: 0,
    contract_name: null,
    contract_ticker_symbol: null,
    contract_address: '0x1e3922cf7fb6a39a546284dc4968940a52ebf99e',
    supports_erc: ['erc20', 'erc1155'],
    logo_url: 'https://logos.covalenthq.com/tokens/1/0x1e3922cf7fb6a39a546284dc4968940a52ebf99e.png',
    last_transferred_at: '2022-06-02T03:12:02Z',
    native_token: false,
    type: 'nft',
    balance: null,
    balance_24h: null,
    quote_rate: 0.0,
    quote_rate_24h: null,
    quote: 0.0,
    quote_24h: null,
    nft_data: [
      {
        token_id: '6',
        token_balance: null,
        token_url: null,
        supports_erc: null,
        token_price_wei: null,
        token_quote_rate_eth: null,
        original_owner: null,
        external_data: null,
        owner: null,
        owner_address: null,
        burned: null,
      }
    ],
  },
];

const additionalContracts = [
  {
    contract_decimals: 0,
    contract_name: 'Lucky Slumdoge',
    contract_ticker_symbol: 'Lucky Slumdoge',
    contract_address: '0x4e4db5faea84264c9fc5a3941ffd96b7e85bef52',
    supports_erc: ['erc20', 'erc1155'],
    logo_url: 'https://logos.covalenthq.com/tokens/1/0x4e4db5faea84264c9fc5a3941ffd96b7e85bef52.png',
    last_transferred_at: '2022-05-20T01:05:49Z',
    native_token: false,
    type: 'nft',
    balance: null,
    balance_24h: null,
    quote_rate: 0.0,
    quote_rate_24h: null,
    quote: 0.0,
    quote_24h: null,
    nft_data: [
      {
        token_id: '784',
        token_balance: null,
        token_url: null,
        supports_erc: null,
        token_price_wei: null,
        token_quote_rate_eth: null,
        original_owner: null,
        external_data: null,
        owner: null,
        owner_address: null,
        burned: null,
      }
    ],
  },
  {
    contract_decimals: 0,
    contract_name: 'Rings for Loot',
    contract_ticker_symbol: 'R4L',
    contract_address: '0x73c5013fa9701425be4a436ca0cec1c0898e6f14',
    supports_erc: ['erc20', 'erc1155'],
    logo_url: 'https://logos.covalenthq.com/tokens/1/0x73c5013fa9701425be4a436ca0cec1c0898e6f14.png',
    last_transferred_at: '2021-12-18T16:29:37Z',
    native_token: false,
    type: 'nft',
    balance: null,
    balance_24h: null,
    quote_rate: 0.0,
    quote_rate_24h: null,
    quote: 0.0,
    quote_24h: null,
    nft_data: [
      {
        token_id: '11',
        token_balance: null,
        token_url: null,
        supports_erc: null,
        token_price_wei: null,
        token_quote_rate_eth: null,
        original_owner: null,
        external_data: null,
        owner: null,
        owner_address: null,
        burned: null,
      },
      {
        token_id: '1',
        token_balance: null,
        token_url: null,
        supports_erc: null,
        token_price_wei: null,
        token_quote_rate_eth: null,
        original_owner: null,
        external_data: null,
        owner: null,
        owner_address: null,
        burned: null,
      }
    ],
  },
  {
    contract_decimals: 0,
    contract_name: 'Zerion Genesis Collection',
    contract_ticker_symbol: 'ZGC',
    contract_address: '0x74ee68a33f6c9f113e22b3b77418b75f85d07d22',
    supports_erc: ['erc20', 'erc1155'],
    logo_url: 'https://logos.covalenthq.com/tokens/1/0x74ee68a33f6c9f113e22b3b77418b75f85d07d22.png',
    last_transferred_at: '2021-07-27T20:43:34Z',
    native_token: false,
    type: 'nft',
    balance: null,
    balance_24h: null,
    quote_rate: 0.0,
    quote_rate_24h: null,
    quote: 0.0,
    quote_24h: null,
    nft_data: [
      {
        token_id: '9',
        token_balance: null,
        token_url: null,
        supports_erc: null,
        token_price_wei: null,
        token_quote_rate_eth: null,
        original_owner: null,
        external_data: null,
        owner: null,
        owner_address: null,
        burned: null,
      }
    ],
  },
];
// Partie 3/3 - Autres contrats et finalisation

const moreContracts = [
  {
    contract_decimals: 0,
    contract_name: 'PLUR Limited',
    contract_ticker_symbol: 'PLUR Limited',
    contract_address: '0x91439cbe7068dffc89780e675c81739b8041d234',
    supports_erc: ['erc20', 'erc1155'],
    logo_url: 'https://logos.covalenthq.com/tokens/1/0x91439cbe7068dffc89780e675c81739b8041d234.png',
    last_transferred_at: '2022-05-31T01:53:04Z',
    native_token: false,
    type: 'nft',
    balance: null,
    balance_24h: null,
    quote_rate: 0.0,
    quote_rate_24h: null,
    quote: 0.0,
    quote_24h: null,
    nft_data: [
      {
        token_id: '2',
        token_balance: null,
        token_url: null,
        supports_erc: null,
        token_price_wei: null,
        token_quote_rate_eth: null,
        original_owner: null,
        external_data: null,
        owner: null,
        owner_address: null,
        burned: null,
      }
    ],
  },
  {
    contract_decimals: 0,
    contract_name: 'Knights of Chains',
    contract_ticker_symbol: 'Knights of Chains',
    contract_address: '0xef05de718fc470987383b7557e1e821ef03a8431',
    supports_erc: ['erc20', 'erc1155'],
    logo_url: 'https://logos.covalenthq.com/tokens/1/0xef05de718fc470987383b7557e1e821ef03a8431.png',
    last_transferred_at: '2022-05-26T22:19:23Z',
    native_token: false,
    type: 'nft',
    balance: null,
    balance_24h: null,
    quote_rate: 0.0,
    quote_rate_24h: null,
    quote: 0.0,
    quote_24h: null,
    nft_data: [
      {
        token_id: '199',
        token_balance: null,
        token_url: null,
        supports_erc: null,
        token_price_wei: null,
        token_quote_rate_eth: null,
        original_owner: null,
        external_data: null,
        owner: null,
        owner_address: null,
        burned: null,
      }
    ],
  },
  {
    contract_decimals: 0,
    contract_name: 'Zapper NFT V2',
    contract_ticker_symbol: 'ZPR NFT',
    contract_address: '0xf1f3ca6268f330fda08418db12171c3173ee39c9',
    supports_erc: ['erc20', 'erc1155'],
    logo_url: 'https://logos.covalenthq.com/tokens/1/0xf1f3ca6268f330fda08418db12171c3173ee39c9.png',
    last_transferred_at: '2022-01-01T20:59:57Z',
    native_token: false,
    type: 'nft',
    balance: null,
    balance_24h: null,
    quote_rate: 0.0,
    quote_rate_24h: null,
    quote: 0.0,
    quote_24h: null,
    nft_data: [
      {
        token_id: '22',
        token_balance: null,
        token_url: null,
        supports_erc: null,
        token_price_wei: null,
        token_quote_rate_eth: null,
        original_owner: null,
        external_data: null,
        owner: null,
        owner_address: null,
        burned: null,
      },
      {
        token_id: '26',
        token_balance: null,
        token_url: null,
        supports_erc: null,
        token_price_wei: null,
        token_quote_rate_eth: null,
        original_owner: null,
        external_data: null,
        owner: null,
        owner_address: null,
        burned: null,
      }
    ],
  }
];
